import {LitElement,html,svg,nothing} from 'lit';
import {repeat} from 'lit/directives/repeat.js';
import catalog from './catalog.json';
import {revision} from './revision.js';
const dataURL=path=>`${path}?v=${revision}`;
import './style.css';
import {fittedAxis} from './axes.js';
const number=n=>n==null?'—':n.toLocaleString();
const modes=[['timeline','Timeline','Follow the recovered record month by month.'],['topics','Topics','See the visual balance across named topics.'],['response','Response map','Reactions horizontally; comments vertically.'],['words','Writing & response','Caption length horizontally; reactions vertically.'],['rank','Ranking','Compare individual posts by public response.'],['palette','Colour','Explore the dominant colour families.'],['format','Format','Group the saved images by their proportions.']];
const detailCache=new Map();
async function getDetail(p){if(!detailCache.has(p.id))detailCache.set(p.id,fetch(dataURL(`data/posts/${p.index}.json`)).then(r=>{if(!r.ok)throw Error('Could not load post');return r.json()}).catch(error=>{detailCache.delete(p.id);throw error}));return {...p,...await detailCache.get(p.id)}}
// Reuse decoded previews for hover, click, reopening, and chart selections.
const previewCache=new Map();
function loadPreview(url){
 if(!url)return Promise.resolve(null);
 if(!previewCache.has(url)){
  const promise=new Promise((resolve,reject)=>{const image=new Image();image.decoding='async';image.onload=async()=>{try{await image.decode()}catch{}resolve(image)};image.onerror=()=>reject(new Error('Preview unavailable'));image.src=url});
  previewCache.set(url,promise);promise.catch(()=>previewCache.delete(url));
 }
 return previewCache.get(url);
}
class PostImage extends LitElement{
 static properties={post:{attribute:false},sheet:{attribute:false},ready:{state:true},failed:{state:true}};
 createRenderRoot(){return this}
 willUpdate(changes){if(changes.has('post')&&changes.get('post')?.id!==this.post?.id){this.ready=false;this.failed=false;this.load()}}
 async load(){const id=this.post?.id;try{await loadPreview(this.post.preview);if(this.post?.id===id)this.ready=true}catch{if(this.post?.id===id)this.failed=true}}
 render(){const p=this.post,s=this.sheet;return html`<div class="dialog-visual" role="img" aria-label=${p.title} style=${`--atlas-image:url("${new URL(s.src,document.baseURI).href}");--atlas-size:${s.cols*100}% ${s.rows*100}%`}><span class="post-thumb instant-preview" style=${`background-position:${p.sprite[0]/(s.cols-1)*100}% ${p.sprite[1]/(s.rows-1)*100}%`}></span>${this.ready&&p.preview?html`<img class="detail-preview" src=${p.preview} alt="" width=${p.width} height=${p.height} decoding="async">`:nothing}</div>${this.failed?html`<button @click=${()=>{this.failed=false;this.load()}}>Retry sharper preview</button>`:nothing}`}
}
customElements.define('post-image',PostImage);
class PostAtlas extends LitElement{
 static properties={posts:{attribute:false},colors:{attribute:false},sprite:{attribute:false},mode:{state:true},query:{state:true},year:{state:true},topic:{state:true},metric:{state:true},focusPost:{state:true},width:{state:true},loading:{state:true}};
 createRenderRoot(){return this} constructor(){super();this.posts=[];this.colors={};this.mode='topics';this.query='';this.year='all';this.topic='all';this.metric='reactions';this.width=1000;this.positions=new Map();this.searchText=null;this.loading=false;this.searchGeneration=0;}
 firstUpdated(){this.resize=new ResizeObserver(entries=>{const w=Math.floor(entries[0].contentRect.width);if(w&&w!==this.width)this.width=w});this.resize.observe(this.querySelector('.atlas-window'));}
 disconnectedCallback(){super.disconnectedCallback();this.resize?.disconnect()}
 async search(e){const q=e.target.value;this.query=q;const generation=++this.searchGeneration;if(q&&!this.searchText){this.loading=true;try{this.searchPromise??=fetch(dataURL('data/search.json')).then(r=>{if(!r.ok)throw Error();return r.json()});this.searchText=await this.searchPromise;}catch{this.searchPromise=null;this.searchError=true}finally{this.loading=false;this.requestUpdate()}}}
 setMode(mode){this.mode=mode;this.focusPost=null;this.querySelector('.atlas-window').scrollTop=0;}
 warm(p,delay=120){this.focusPost=p;clearTimeout(this.warmTimer);this.warmTimer=setTimeout(()=>this.dispatchEvent(new CustomEvent('warm-post',{detail:p,bubbles:true})),delay)}
 select(p){this.dispatchEvent(new CustomEvent('open-post',{detail:p,bubbles:true}))}
 layout(){
 const key=[this.mode,this.query,this.year,this.topic,this.metric,this.width,!!this.searchText].join('|');if(this.layoutCache?.key===key)return this.layoutCache.value;
 const q=this.query.toLowerCase();let rows=this.posts.filter(p=>(this.year==='all'||p.year===this.year)&&(this.topic==='all'||p.topic===this.topic)&&(!q||`${p.title} ${this.searchText?.[p.id]||''}`.toLowerCase().includes(q)));
 const missing=[],w=this.width,mobile=w<600,labels=[],positions=new Map();let h=0,axes=null;
 if(['response','words'].includes(this.mode)){
 const xkey=this.mode==='words'?'words':'reactions',ykey=this.mode==='words'?'reactions':'comments';const known=rows.filter(p=>typeof p[xkey]==='number'&&typeof p[ykey]==='number');missing.push(...rows.filter(p=>!known.includes(p)));const left=48,right=w-25,top=50,bottom=mobile?500:560,size=mobile?24:32;
 const fitted=this.mode==='words';
 const axisFor=key=>{if(fitted)return fittedAxis(known.map(p=>p[key]),mobile?4:6);const max=Math.max(1,...known.map(p=>p[key]));return {scale:v=>Math.log1p(v)/Math.log1p(max),ticks:[0,1,5,10,25,50,100,250,500,1000,2500,5000].filter(v=>v<=max)}};
 const xAxis=axisFor(xkey),yAxis=axisFor(ykey),x=v=>left+xAxis.scale(v)*(right-left),y=v=>bottom-yAxis.scale(v)*(bottom-top);
 known.forEach(p=>positions.set(p.id,{x:x(p[xkey])-size/2,y:y(p[ykey])-size/2,w:size,h:size}));
 axes={x:xAxis.ticks.map(v=>({v,pos:x(v)})),y:yAxis.ticks.map(v=>({v,pos:y(v)})),left,right,top,bottom,xkey,ykey,fitted};h=bottom+65;
 }else if(this.mode==='rank'){
 const known=rows.filter(p=>typeof p[this.metric]==='number').sort((a,b)=>b[this.metric]-a[this.metric]||a.index-b.index);missing.push(...rows.filter(p=>!known.includes(p)));const max=Math.max(1,...known.map(p=>p[this.metric]));known.forEach((p,i)=>{positions.set(p.id,{x:14,y:20+i*68,w:48,h:48,bar:(w-100)*p[this.metric]/max});labels.push({x:76,y:39+i*68,text:`${number(p[this.metric])} ${this.metric}`,sub:p.title.slice(0,mobile?25:80),rank:i+1})});h=known.length*68+35;
 }else{
 const key=this.mode==='timeline'?'month':this.mode==='topics'?'topic':this.mode==='palette'?'palette':'shape';const groups=new Map();[...rows].sort((a,b)=>a.date.localeCompare(b.date)||a.index-b.index).forEach(p=>{const k=key==='shape'?p.width/p.height<.9?'Portrait':p.width/p.height>1.1?'Landscape':'Near square':p[key];if(!groups.has(k))groups.set(k,[]);groups.get(k).push(p)});
 const list=[...groups].sort((a,b)=>this.mode==='timeline'?a[0].localeCompare(b[0]):b[1].length-a[1].length);const cols=Math.max(3,Math.floor((w-24)/(mobile?65:78))),gap=8,size=Math.floor((w-24-(cols-1)*gap)/cols);let y=18;
 list.forEach(([name,posts])=>{const title=key==='month'?new Date(name+'-02').toLocaleDateString('en',{month:'long',year:'numeric'}):name;labels.push({x:12,y:y+16,text:title,sub:`${posts.length} posts`});y+=49;posts.forEach((p,i)=>positions.set(p.id,{x:12+(i%cols)*(size+gap),y:y+Math.floor(i/cols)*(size+gap),w:size,h:size}));y+=Math.ceil(posts.length/cols)*(size+gap)+30});h=y;
 }
 this.positions=positions;this.currentRows=rows;const value={rows:rows.filter(p=>positions.has(p.id)),labels,positions,h:Math.max(220,h),axes,missing};this.layoutCache={key,value};return value;
 }
 render(){const l=this.layout(),mode=modes.find(m=>m[0]===this.mode),mobile=this.width<600;
 return html`<div class="atlas-controls"><div class="view-tabs" role="group" aria-label="Atlas layout">${modes.map(([id,name])=>html`<button aria-pressed=${this.mode===id} @click=${()=>this.setMode(id)}>${name}</button>`)}</div><div class="filters"><label class="search">Search posts<input type="search" placeholder="Search full captions…" .value=${this.query} @input=${e=>this.search(e)}></label><div class="year-filter"><span>Year</span><div role="group" aria-label="Year">${['all','2023','2024','2025','2026'].map(y=>html`<button aria-pressed=${this.year===y} @click=${()=>{this.year=y;this.querySelector('.atlas-window').scrollTop=0}}>${y==='all'?'All':y}</button>`)}</div></div><label>Topic<select aria-label="Topic" .value=${this.topic} @change=${e=>{this.topic=e.target.value;this.querySelector('.atlas-window').scrollTop=0}}><option value="all">All topics</option>${Object.keys(this.colors).map(t=>html`<option>${t}</option>`)}</select></label>${this.mode==='rank'?html`<label>Rank by<select aria-label="Rank by" .value=${this.metric} @change=${e=>this.metric=e.target.value}><option value="reactions">Reactions</option><option value="comments">Comments</option></select></label>`:nothing}${this.query||this.year!=='all'||this.topic!=='all'?html`<button class="reset" @click=${()=>{this.query='';this.year='all';this.topic='all'}}>Clear filters</button>`:nothing}</div></div>
 <div class="atlas-caption"><p>${mode[2]} ${l.axes?(l.axes.fitted?'Axes fit the selected posts and update with filters. Equal distances represent equal changes; overlapping images share similar values.':'Logarithmic spacing keeps low and high values visible; overlapping images share similar values.'):''}</p><span role="status">${this.loading?'Searching captions…':this.searchError?'Caption search unavailable · searching titles':`${l.positions.size} of ${this.posts.length} posts`}</span></div>
 <div class="atlas-window" tabindex="0" aria-label="Scrollable post visualization"><div class="atlas-stage" style=${`height:${l.h}px;--atlas-image:url("${new URL(this.sprite.src,document.baseURI).href}");--atlas-size:${this.sprite.cols*100}% ${this.sprite.rows*100}%`}>
 <svg class="atlas-guides" width=${this.width} height=${l.h} aria-hidden="true">${l.axes?svg`${l.axes.x.map(t=>svg`<line x1=${t.pos} x2=${t.pos} y1=${l.axes.top} y2=${l.axes.bottom}/><text x=${t.pos} y=${l.axes.bottom+25} text-anchor="middle">${t.v}</text>`)}${l.axes.y.map(t=>svg`<line x1=${l.axes.left} x2=${l.axes.right} y1=${t.pos} y2=${t.pos}/><text x=${l.axes.left-8} y=${t.pos+4} text-anchor="end">${t.v}</text>`)}<text x=${l.axes.left} y="20">${l.axes.ykey==='comments'?'Comments':'Reactions'}</text><text x=${(l.axes.left+l.axes.right)/2} y=${l.axes.bottom+52} text-anchor="middle">${l.axes.xkey==='words'?'Caption words':'Reactions'}${l.axes.fitted?'':' · log(1 + value)'}</text>`:nothing}${l.labels.map(t=>svg`<text class="group-label" x=${t.x} y=${t.y}>${t.text}</text><text class="group-sub" x=${this.mode==='rank'?t.x:this.width-12} y=${this.mode==='rank'?t.y+19:t.y} text-anchor=${this.mode==='rank'?'start':'end'}>${t.sub}</text>`)}</svg>
 ${repeat(this.posts,p=>p.id,p=>{const pos=l.positions.get(p.id);return html`<button class="post-icon ${l.axes?'scatter-icon':''}" ?hidden=${!pos} style=${pos?`transform:translate(${pos.x}px,${pos.y}px);width:${pos.w}px;height:${pos.h}px;--topic:${this.colors[p.topic]||'#748b99'}`:''} aria-label=${`Post ${p.index}, ${p.date}: ${p.title}. ${number(p.reactions)} reactions, ${number(p.comments)} comments`} @click=${()=>this.select(p)} @pointerenter=${()=>this.warm(p)} @pointerleave=${()=>clearTimeout(this.warmTimer)} @focus=${()=>this.warm(p,0)}>${p.image?html`<span class="post-thumb" aria-hidden="true" data-post-id=${p.id} style=${`background-position:${p.sprite[0]/(this.sprite.cols-1)*100}% ${p.sprite[1]/(this.sprite.rows-1)*100}%`}></span>`:html`<span class="no-image">Text<br>only</span>`}${!l.axes&&this.mode!=='rank'?html`<span class="post-index">${p.index}</span>`:nothing}${this.mode==='rank'&&pos?html`<span class="rank-bar" style=${`width:${pos.bar}px`}></span>`:nothing}</button>`})}
 ${!l.positions.size?html`<p class="no-results">No matching posts. Try another search or clear the filters.</p>`:nothing}</div></div>
 <div class="atlas-inspector" aria-live="polite">${this.focusPost?html`<span class="inspector-index">#${this.focusPost.index}</span><div><strong>${this.focusPost.title}</strong><small>${this.focusPost.date} · ${number(this.focusPost.reactions)} reactions · ${number(this.focusPost.comments)} comments</small></div><button @click=${()=>this.select(this.focusPost)}>Read post ↗</button>`:html`<span>Select an image to read its caption and inspect its counters. Image proportions are preserved.</span>`}</div>
 ${l.missing.length?html`<details class="missing"><summary>${l.missing.length} posts lack the counters needed for this view</summary>${l.missing.map(p=>html`<button @click=${()=>this.select(p)}>#${p.index} ${p.title}</button>`)}</details>`:nothing}
 <details class="text-index"><summary>Browse this selection as an accessible text list (${l.rows.length})</summary><div>${l.rows.map(p=>html`<button @click=${()=>this.select(p)}><small>#${p.index} · ${p.date}</small>${p.title}<small>${number(p.reactions)} reactions · ${number(p.comments)} comments</small></button>`)}</div></details>`;
 }
}
customElements.define('post-atlas',PostAtlas);
class SocialReport extends LitElement{
 static properties={data:{state:true},error:{state:true},selected:{state:true},detailLoading:{state:true}};
 createRenderRoot(){return this}constructor(){super();this.data=null;this.selected=null;this.error='';this.addEventListener('open-post',e=>this.openPost(e.detail));this.addEventListener('warm-post',e=>{loadPreview(e.detail.preview).catch(()=>{});getDetail(e.detail).catch(()=>{})});}
 async connectedCallback(){super.connectedCallback();try{this.data=JSON.parse(document.querySelector('#atlas-data').textContent);await this.updateComplete;this.watchAnalysis();this.handleHash();addEventListener('hashchange',()=>this.handleHash())}catch{this.error='The data could not load. Please reload the page.'}}
 async handleHash(){const aliases={f06:'rank',f19:'timeline',f20:'topics',f21:'palette',f22:'rank',f30:'format',library:'timeline'};const hash=location.hash.slice(1);if(aliases[hash]){this.querySelector('post-atlas')?.setMode(aliases[hash]);this.querySelector('#atlas')?.scrollIntoView()}else if(hash){const target=this.querySelector('#'+CSS.escape(hash));if(target?.matches('article.figure'))await this.mountChart(target);requestAnimationFrame(()=>requestAnimationFrame(()=>target?.scrollIntoView()))}}
 async openPost(p){p={...p,...this.data.posts.find(row=>row.id===p.id)};this.selected=p;this.detailLoading=typeof p.caption!=='string';await this.updateComplete;const dlg=this.querySelector('#post-dialog');if(!dlg.open)dlg.showModal();if(!this.detailLoading)return;try{const detail=await getDetail(p);if(this.selected?.id===p.id)this.selected=detail}catch{if(this.selected?.id===p.id)this.selected={...p,caption:'Caption could not load. Please reopen this post to retry.'};detailCache.delete(p.id)}finally{if(this.selected?.id===p.id)this.detailLoading=false}}
 watchAnalysis(){let setupPromise;const load=()=>setupPromise??=Promise.all([import('./analysis.js'),import('./analysis.css'),fetch(dataURL('data/analysis.json')).then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([module,css,data])=>module.createAnalysis(data,p=>this.openPost(p)));
 this.chartJobs=new Map();this.mountChart=el=>{if(!this.chartJobs.has(el.id))this.chartJobs.set(el.id,load().then(setup=>{el.querySelector('.chart-placeholder')?.remove();setup(el);el.dataset.ready='true'}).catch(err=>{const placeholder=el.querySelector('.chart-placeholder');if(placeholder)placeholder.textContent='Chart could not load. Reload the page to retry.';console.error(err)}));return this.chartJobs.get(el.id)};
 this.chartObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){this.chartObserver.unobserve(e.target);this.mountChart(e.target)}}),{rootMargin:'100px'});this.querySelectorAll('article.figure').forEach(el=>this.chartObserver.observe(el));}

 render(){if(!this.data)return html`<p class="boot">${this.error||'Loading the post atlas…'}</p>`;const p=this.selected;return html`
 <a class="skip" href="#atlas">Skip to post atlas</a><header><a class="brand" href="#">RIAD MEDDEB <span>/ LINKEDIN</span></a><nav><a href="#atlas">Post atlas</a><a href="#report">Analysis</a><a href="#method">Method</a></nav></header><main>
 <section class="hero"><div class="eyebrow">March 2023 — September 2026</div><h1>Riad Meddeb’s<br><em>LinkedIn presence</em></h1><p>The topics he covers, how his writing has changed, and which posts attract reactions and comments.</p><div class="hero-bottom"><div><strong>277</strong> recovered posts <span>·</span> <strong>276</strong> main visuals</div><a href="Riad_Meddeb_LinkedIn_Visual_Analysis.docx">Read the report ↗</a></div></section>
 <section id="atlas" class="atlas-section"><div class="section-heading"><div><span class="eyebrow">01 / Explore the posts</span><h2>Explore the post archive</h2></div><p>Every image is a post.<br>Change the view to follow a different question.</p></div><post-atlas .posts=${this.data.posts} .colors=${this.data.colors} .sprite=${this.data.sprite}></post-atlas></section>
 <section id="report"><div class="section-heading"><div><span class="eyebrow">02 / Read the analysis</span><h2>Patterns behind the posts</h2></div><p>Topic comparisons, writing patterns and public response, with the source posts one click away.</p></div><div class="analysis-nav"><label>Go to analysis<select @change=${e=>{if(e.target.value){location.hash=e.target.value;e.target.value=''}}}><option value="">Choose a chart</option>${catalog.map(f=>html`<option value=${f.id}>${f.id==='f15'?'How much response comes from the top posts?':f.title}</option>`)}</select></label><span>${catalog.length} analyses · charts load as you reach them</span></div>
 ${catalog.map(f=>html`<article class="figure" id=${f.id}><div class="figureheader"><span class="eyebrow">${f.chapter} / ${String(f.number).padStart(2,'0')}</span><h2>${f.id==='f15'?'How much response comes from the top posts?':f.title}</h2></div><div class="figuretext"><p>${f.analysis}</p></div><div class="chart-placeholder" aria-label="Chart loads when visible"></div><details class="figure-note"><summary>Sample and interpretation</summary><p>${f.note}</p><a href=${`d3_figures/${f.id}.svg`}>Original report figure ↗</a></details></article>`)}</section>
 <section id="method" class="method"><span class="eyebrow">03 / Sources & files</span><h2>What the record can tell us</h2><p>The expanded archive contains 277 recovered records. Original caption comparisons use 235 eligible English captions; response rankings use 246 original activities with both counters, excluding reposts. The atlas shows the expanded record and uses known counters for its response views.</p><p>Baseline counters were collected on 1 October 2026 UTC and browser checks made on 2 October. They are cumulative public counts, not reach or engagement rates. Missing counters are unknown. The 2023 sample is incomplete; recovered counts do not establish annual posting totals. Full-account completeness remains unverified. Twenty additions lack resolved activity IDs and all 21 additions lack independently resolved exact UTC times.</p><p>Colour families describe image pixels, not semantic meaning. The saved visual may be a document or video cover. One post has no standalone visual. Images retain their original aspect ratios.</p><div class="downloads"><a href="Riad_Meddeb_Expanded_Dataset.xlsx">Spreadsheet ↗</a><a href="Riad_Meddeb_Expanded_Dataset.csv">Post data · CSV ↗</a><a href="Riad_Meddeb_LinkedIn_Visual_Analysis.docx">Word report ↗</a><a href="Image_Manifest.csv">Image manifest ↗</a><a href="Figure_Source_Manifest.csv">Figure sources ↗</a></div></section><footer>Prepared from the supplied package and signed-in browser audit. Built with Lit and D3.</footer></main>
 <dialog id="post-dialog" @click=${e=>{if(e.target===e.currentTarget)e.currentTarget.close()}}><button class="close" @click=${()=>this.querySelector('#post-dialog').close()}>Close ×</button>${p?html`<div class="dialoggrid"><div>${p.image?html`<post-image .post=${p} .sheet=${this.data.sprite}></post-image>`:html`<p>No standalone visual.</p>`}</div><div><span class="eyebrow">POST ${p.index} · ${p.date}</span><h2>${p.title}</h2><p>${p.topic}</p><div class="counters"><span><strong>${number(p.reactions)}</strong>reactions</span><span><strong>${number(p.comments)}</strong>comments</span></div><p class="caption">${this.detailLoading?'Loading caption…':p.caption||p.sharedText||'No author caption recovered.'}</p><p class="counter-note">Package counters above. Browser check: ${number(p.liveReactions)} reactions / ${number(p.liveComments)} comments.</p><div class="downloads">${p.source?html`<a href=${p.source} target="_blank" rel="noopener">LinkedIn source ↗</a>`:nothing}${p.image?html`<a href=${p.image} target="_blank" rel="noopener">Original image ↗</a>`:nothing}</div></div></div>`:nothing}</dialog>`}
}
customElements.define('social-report',SocialReport);
