/* Data exploration: all computations use documented source samples. */
const exploreRows=C.map(r=>index.get(r.activity_id)).filter(Boolean);
const rankRows=R.map(r=>index.get(r.activity_id)).filter(Boolean);
const numeric=(p,k)=>typeof p[k]==='number'&&Number.isFinite(p[k]);
const medianOf=(rows,k)=>{const v=rows.filter(p=>numeric(p,k));return v.length>=3?d3.median(v,p=>p[k]):null};
const totalOf=(rows,k)=>d3.sum(rows.filter(p=>numeric(p,k)),p=>p[k]);
const unique=key=>[...new Set(P.map(p=>p[key]))].filter(Boolean);
const escMetric={count:'Posts',reactions:'Median reactions',comments:'Median comments',words:'Median caption words',share:'Share of comments',ai:'AI mentions (%)',jaccard:'Overlap (%)'};
let exploreYear='all';
const explorers=[];
const lens=d3.select('#report').append('div').attr('class','year-lens');
lens.append('span').text('Explore recovered records:');
['all',...years].forEach(y=>lens.append('button').attr('type','button').attr('aria-pressed',y==='all').text(y==='all'?'All':y).on('click',function(){exploreYear=y;lens.selectAll('button').attr('aria-pressed',function(){return this.textContent===(y==='all'?'All':y)});explorers.forEach(v=>v.draw());}));
lens.append('small').text('Changes the explorers below. Historical coverage is incomplete, especially 2023.');
const hover=d3.select('body').append('div').attr('class','data-tooltip').attr('hidden',true).attr('role','tooltip');
function openRowsDialog(rows,label){
 const dlg=document.querySelector('#records-dialog');d3.select('#records-title').text(label);d3.select('#records-count').text(`${rows.length} underlying records · select a post to read its caption`);
 const list=d3.select('#records-list');list.html('');rows.forEach(p=>{const b=list.append('button').attr('class','record-row').on('click',()=>{dlg.close();showPost(p)});if(p.embedded)b.append('img').attr('src',p.embedded).attr('alt','').attr('loading','lazy');const t=b.append('span');t.append('small').text(`${p.date} · #${p.index}`);t.append('strong').text(p.title);t.append('small').text(`${fmt(p.reactions)} reactions · ${fmt(p.comments)} comments`)});
 document.querySelector('#records-download').onclick=()=>{const csv=d3.csvFormat(rows.map(p=>({index:p.index,date:p.date,title:p.title,caption:p.caption,topic:p.topic,approach:p.approach,reactions:p.reactions,comments:p.comments,url:p.source})));saveBlob(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}),'selected-posts.csv')};dlg.showModal();dlg.scrollTop=0;
}
const records=d3.select('body').append('dialog').attr('id','records-dialog').attr('aria-labelledby','records-title');records.append('button').attr('class','close').attr('aria-label','Close records').text('Close ×').on('click',()=>records.node().close());records.append('h2').attr('id','records-title');records.append('p').attr('id','records-count');records.append('button').attr('id','records-download').text('Download these records');records.append('div').attr('id','records-list');
function control(v,name,options,initial){const label=v.controls.append('label');label.append('span').text(name);const sel=label.append('select').attr('aria-label',`${name} — figure ${v.spec.number}`).attr('data-control',name==='Sort by'?'sort':null);options.forEach(o=>{const [key,text]=Array.isArray(o)?o:[o,o];sel.append('option').attr('value',key).text(text)});sel.property('value',initial??(Array.isArray(options[0])?options[0][0]:options[0]));sel.on('change',()=>v.draw());return ()=>sel.property('value')}
function metricOptions(extra=[]){return [['reactions','Reactions'],['comments','Comments'],...extra]}
function addSelection(v,label,rows,value){v.selection.html('');v.selection.append('strong').text(label);if(value)v.selection.append('span').text(value);v.selection.append('button').text(`Read ${rows.length} posts →`).property('disabled',!rows.length).on('click',()=>openRowsDialog(rows,label));}
function mark(sel,v,label,rows,value){sel.attr('tabindex',0).attr('role','button').attr('aria-label',label+' · '+value+' · inspect records').style('cursor','pointer').on('pointerenter',e=>{hover.text(label+' · '+value).attr('hidden',null);const box=hover.node().getBoundingClientRect();hover.style('left',Math.max(8,Math.min(e.clientX+12,innerWidth-box.width-8))+'px').style('top',Math.max(8,Math.min(e.clientY+12,innerHeight-box.height-8))+'px');}).on('pointerleave',()=>hover.attr('hidden',true)).on('click',()=>{hover.attr('hidden',true);v.chart.selectAll('.chosen').classed('chosen',false);sel.classed('chosen',true);addSelection(v,label,rows,value)}).on('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();addSelection(v,label,rows,value)}});return sel}
function base(v,h=330){const w=Math.max(260,Math.round(v.chart.node().clientWidth));const s=v.chart.append('svg').attr('viewBox',`0 0 ${w} ${h}`).attr('width',w).attr('height',h).attr('aria-label',v.spec.title+' interactive exploration').attr('role','group');s.append('rect').attr('width',w).attr('height',h).attr('fill','white');return {s,w,h}}
function label(g,x,y,t,size=12,fill=ink,anchor='start',weight=400){return g.append('text').attr('x',x).attr('y',y).attr('font-size',size).attr('font-family','Arial,sans-serif').attr('fill',fill).attr('text-anchor',anchor).attr('font-weight',weight).text(t)}
function measure(rows,k){return k==='count'?rows.length:k==='ai'?(rows.length?d3.mean(rows,p=>Number(p.baseline?.ai_mention))*100:null):medianOf(rows,k)}
function categoryBars(v,rows,key,metric,order='value',barColor=null){
 const groups=d3.groups(rows,p=>p[key]).map(([name,posts])=>({name,posts,value:metric==='share'?(totalOf(rows,'comments')?totalOf(posts,'comments')/totalOf(rows,'comments')*100:null):measure(posts,metric)}));groups.sort(v.categoryOrder?(a,b)=>v.categoryOrder.indexOf(a.name)-v.categoryOrder.indexOf(b.name):order==='name'?(a,b)=>a.name.localeCompare(b.name):(a,b)=>(b.value??-1)-(a.value??-1));
 const {s,w}=base(v,groups.length*62+30),left=16,right=w-20,x=d3.scaleLinear().domain([0,d3.max(groups,g=>g.value)||1]).range([left,right]);
 groups.forEach((g,i)=>{const y=20+i*62;label(s,left,y,g.name,13,ink,'start',600);label(s,right,y,`${g.value==null?'n < 3':fmt(g.value)+(metric==='share'||metric==='ai'?'%':'')} · n=${g.posts.length}`,12,muted,'end');s.append('rect').attr('x',left).attr('y',y+10).attr('width',right-left).attr('height',18).attr('rx',3).attr('fill','#EDF2F7');if(g.value!=null)s.append('rect').attr('x',left).attr('y',y+10).attr('width',Math.max(2,x(g.value)-left)).attr('height',18).attr('rx',3).attr('fill',barColor||D.colors[g.name]||YC[g.name]||(metric==='comments'?red:blue));mark(s.append('rect').attr('x',left).attr('y',y-15).attr('width',right-left).attr('height',53).attr('fill','transparent'),v,g.name,g.posts,`${escMetric[metric]||metric}: ${g.value==null?'insufficient sample':fmt(g.value)}`)});
 v.insight.text(metric==='count'?`${rows.length} records, regrouped by ${key}. Select any bar to inspect its posts.`:`${escMetric[metric]} recalculated for this selection. Medians need at least three known values.`);
}
function calendar(v,rows,metric){const ys=exploreYear==='all'?years:[exploreYear],{s,w}=base(v,ys.length*90+66),left=42,cw=(w-left-12)/12;d3.range(12).forEach(i=>label(s,left+(i+.5)*cw,20,'JFMAMJJASOND'[i],11,muted,'middle'));const groups=ys.flatMap(year=>d3.range(12).map(m=>{const month=year+'-'+String(m+1).padStart(2,'0');const posts=rows.filter(p=>p.month===month);return {year,month,m,posts,value:measure(posts,metric)}}));const color=d3.scaleSequential(t=>d3.interpolateRgb('#E8F2FA',metric==='comments'?red:blue)(t)).domain([0,d3.max(groups,g=>g.value)||1]);groups.forEach(g=>{const y=32+ys.indexOf(g.year)*90,x=left+g.m*cw;const valid=g.month>='2023-03'&&g.month<='2026-09';if(!g.m)label(s,5,y+25,g.year,12,ink,'start',600);const fill=!valid||g.value==null?'#EDF1F5':color(g.value);const rect=s.append('rect').attr('x',x).attr('y',y).attr('width',cw-3).attr('height',52).attr('rx',4).attr('fill',fill);mark(rect,v,g.month,g.posts,valid?(g.value==null?'n < 3':`${escMetric[metric]}: ${fmt(g.value)}`):'Outside recovered date range');label(s,x+(cw-3)/2,y+29,valid&&g.value!=null?fmt(g.value):'–',cw<25?9:12,lightLabel(fill)?'white':ink,'middle',600).style('pointer-events','none')});v.insight.text(metric==='count'?'Select a month to read its recovered posts. Zero means no recovered record, not proof of inactivity.':'Cells show medians for eligible captions; fewer than three known observations are left blank.');}
function timeline(v,rows,metric,interval){const key=p=>interval==='quarter'?p.year+' Q'+Math.ceil(Number(p.month.slice(5))/3):p.month;const periodMap=d3.group(rows,key),months=d3.utcMonth.range(new Date('2023-03-01'),new Date('2026-10-01')).map(d=>d3.utcFormat('%Y-%m')(d)).filter(m=>exploreYear==='all'||m.startsWith(exploreYear)),periods=[...new Set(months.map(m=>interval==='quarter'?m.slice(0,4)+' Q'+Math.ceil(Number(m.slice(5))/3):m))],groups=periods.map(name=>{const posts=periodMap.get(name)||[];return {name,posts,value:measure(posts,metric)}});const {s,w,h}=base(v,310),x=d3.scalePoint().domain(groups.map(g=>g.name)).range([48,w-20]),y=d3.scaleLinear().domain([0,d3.max(groups,g=>g.value)||1]).nice().range([h-55,25]);s.append('g').attr('transform','translate(48,0)').call(d3.axisLeft(y).ticks(4).tickSize(-(w-68))).call(g=>g.select('.domain').remove()).call(g=>g.selectAll('line').attr('stroke',grid));const ticks=groups.filter((_,i)=>i%Math.max(1,Math.ceil(groups.length/(w<500?4:10)))===0).map(g=>g.name);s.append('g').attr('transform',`translate(0,${h-55})`).call(d3.axisBottom(x).tickValues(ticks).tickSize(0)).selectAll('text').attr('font-size',10);s.append('path').datum(groups).attr('d',d3.line().defined(g=>g.value!=null).x(g=>x(g.name)).y(g=>y(g.value))).attr('fill','none').attr('stroke',metric==='comments'?red:blue).attr('stroke-width',3);groups.filter(g=>g.value!=null).forEach(g=>mark(s.append('circle').attr('cx',x(g.name)).attr('cy',y(g.value)).attr('r',6).attr('fill',metric==='comments'?red:blue).attr('stroke','white').attr('stroke-width',2),v,g.name,g.posts,`${escMetric[metric]}: ${fmt(g.value)} · n=${g.posts.length}`));v.insight.text(`Grouped by ${interval}. Select a point to open that period’s posts. Gaps and medians reflect the recovered sample.`);}
function matrix(v,rows,rowKey,colKey,metric){const rr=[...new Set(rows.map(p=>p[rowKey]))],cc=[...new Set(rows.map(p=>p[colKey]))];const {s,w}=base(v,rr.length*55+95);const left=w<500?100:180,cw=(w-left-12)/Math.max(1,cc.length);cc.forEach((c,i)=>label(s,left+(i+.5)*cw,35,colKey==='year'?c:String(i+1),12,ink,'middle',600));let cells=rr.flatMap(r=>cc.map(c=>{const posts=rows.filter(p=>p[rowKey]===r&&p[colKey]===c);return {r,c,posts,value:measure(posts,metric)}}));const color=d3.scaleLinear().domain([0,d3.max(cells,g=>g.value)||1]).range(['#EAF3FA',metric==='comments'?red:blue]);cells.forEach(g=>{const y=48+rr.indexOf(g.r)*55,x=left+cc.indexOf(g.c)*cw,fill=g.value==null?'#EDF1F5':color(g.value);if(g.c===cc[0])wrap(s,left-9,y+21,g.r,left-15,w<500?11:13,ink).attr('text-anchor','end');mark(s.append('rect').attr('x',x).attr('y',y).attr('width',cw-3).attr('height',48).attr('rx',3).attr('fill',fill),v,g.r+' · '+g.c,g.posts,`${escMetric[metric]}: ${g.value==null?'n < 3':fmt(g.value)}`);label(s,x+(cw-3)/2,y+22,g.value==null?'–':fmt(g.value),cw<32?10:13,lightLabel(fill)?'white':ink,'middle',600).style('pointer-events','none');if(cw>=32)label(s,x+(cw-3)/2,y+39,'n='+g.posts.length,10,lightLabel(fill)?'white':ink,'middle').style('pointer-events','none')});if(colKey!=='year')v.key.text(cc.map((c,i)=>`${i+1}. ${c}`).join('   ·   '));v.insight.text('Select a cell to see exactly which posts form it. Blank medians have fewer than three known observations.');}
function scatterExplore(v,rows,xkey,metric){const {s,w,h}=base(v,360),x=d3.scaleLinear().domain([0,d3.max(rows,p=>p[xkey])||1]).nice().range([48,w-18]),y=d3.scaleLinear().domain([0,d3.max(rows,p=>p[metric])||1]).nice().range([h-55,28]);const valid=rows.filter(p=>numeric(p,xkey)&&numeric(p,metric));s.append('g').attr('transform',`translate(0,${h-55})`).call(d3.axisBottom(x).ticks(w<500?4:7));s.append('g').attr('transform','translate(48,0)').call(d3.axisLeft(y).ticks(5).tickSize(-(w-66))).call(g=>g.selectAll('line').attr('stroke',grid));label(s,w/2,h-10,xkey==='words'?'Caption words':'Reactions',12,muted,'middle');label(s,48,15,metric==='comments'?'Comments':'Reactions',12,muted);const layer=s.append('g');const dots=layer.selectAll('circle').data(valid).join('circle').attr('cx',p=>x(p[xkey])).attr('cy',p=>y(p[metric])).attr('r',5).attr('fill',p=>D.colors[p.topic]||blue).attr('opacity',.8);dots.each(function(p){mark(d3.select(this),v,p.title,[p],`${p[xkey]} ${xkey} · ${p[metric]} ${metric}`)});
 const enabled=v.brushMode?.()==='select';if(enabled){s.append('g').attr('class','brush').call(d3.brush().extent([[48,28],[w-18,h-55]]).on('end',event=>{if(!event.selection){dots.attr('opacity',.8);v.selection.html('');return;}const [[x0,y0],[x1,y1]]=event.selection;const selected=valid.filter(p=>x(p[xkey])>=x0&&x(p[xkey])<=x1&&y(p[metric])>=y0&&y(p[metric])<=y1);dots.attr('opacity',p=>selected.includes(p)?1:.12);addSelection(v,'Selected region',selected,`${selected.length} posts in the selected range`)}));}v.insight.text(enabled?'Drag a rectangle around a cluster to collect and read those posts.':'Select a dot to inspect its post, or switch to Select a region to investigate a cluster.');}
function distribution(v,rows,metric){const groups=d3.groups(rows,p=>p.topic).sort((a,b)=>(medianOf(b[1],metric)??-1)-(medianOf(a[1],metric)??-1)),{s,w}=base(v,groups.length*75+42),x=d3.scaleLinear().domain([0,d3.max(rows,p=>p[metric])||1]).range([16,w-20]);groups.forEach(([name,posts],i)=>{const y=20+i*75;label(s,16,y,name,12,ink,'start',600);const known=posts.filter(p=>numeric(p,metric)),m=medianOf(posts,metric);label(s,w-20,y,`median ${fmt(m)} · n=${known.length}`,11,muted,'end');known.forEach((p,j)=>mark(s.append('circle').attr('cx',x(p[metric])).attr('cy',y+28+((j*7)%13-6)).attr('r',4).attr('fill',D.colors[name]||blue).attr('opacity',.7),v,p.title,[p],`${p[metric]} ${metric}`));if(m!=null)s.append('line').attr('x1',x(m)).attr('x2',x(m)).attr('y1',y+14).attr('y2',y+44).attr('stroke',ink).attr('stroke-width',3)});s.append('g').attr('transform',`translate(0,${groups.length*75+7})`).call(d3.axisBottom(x).ticks(5));v.insight.text('Topics reorder by median. Each dot is a post; the dark line marks its group’s median.');}
function compareYears(v,rows,key,metric,yearA,yearB){const groups=unique(key).filter(name=>rows.some(p=>p[key]===name)),{s,w}=base(v,groups.length*75+30);const max=d3.max(groups.flatMap(name=>[yearA,yearB].map(y=>measure(rows.filter(p=>p[key]===name&&p.year===y),metric))))||1,x=d3.scaleLinear().domain([0,max]).range([16,w-20]);groups.forEach((name,i)=>{const a=rows.filter(p=>p[key]===name&&p.year===yearA),b=rows.filter(p=>p[key]===name&&p.year===yearB),va=measure(a,metric),vb=measure(b,metric),y=20+i*75;label(s,16,y,name,12,ink,'start',600);label(s,w-20,y,va!=null&&vb!=null?`Δ ${d3.format('+.1f')(vb-va)}`:'Insufficient sample',11,muted,'end');if(va!=null&&vb!=null)s.append('line').attr('x1',x(va)).attr('x2',x(vb)).attr('y1',y+28).attr('y2',y+28).attr('stroke',grid).attr('stroke-width',5);[[yearA,a,va,blue],[yearB,b,vb,red]].forEach(([yr,posts,val,color],j)=>{if(val!=null){mark(s.append('circle').attr('cx',x(val)).attr('cy',y+28).attr('r',7).attr('fill',color),v,name+' · '+yr,posts,`${escMetric[metric]}: ${fmt(val)}`);label(s,x(val),y+(j?52:15),fmt(val),11,color,'middle')}})});v.key.text(`● ${yearA}: blue    ● ${yearB}: red · Δ = ${yearB} minus ${yearA}`);v.insight.text('Compare like-for-like groups across two selected years. Sparse medians are omitted; unequal archive coverage still limits interpretation.');}
function featureCompare(v,rows,metric,onlyQuestion=false){const fields=onlyQuestion?[['question_any','Question anywhere']]:[['question_opening','Opening question'],['external_link','External link'],['ai_mention','AI mention'],['first_person','First person']];const {s,w}=base(v,fields.length*96+30),max=d3.max(fields.flatMap(([k])=>[true,false].map(flag=>medianOf(rows.filter(p=>!!p.baseline?.[k]===flag),metric))))||1,x=d3.scaleLinear().domain([0,max]).range([16,w-155]);fields.forEach(([key,name],i)=>{let y=22+i*96;label(s,16,y,name,13,ink,'start',600);[false,true].forEach((flag,j)=>{const posts=rows.filter(p=>!!p.baseline?.[key]===flag),val=medianOf(posts,metric),yy=y+20+j*26;const color=flag?red:blue;if(val!=null)mark(s.append('rect').attr('x',16).attr('y',yy).attr('width',Math.max(2,x(val)-16)).attr('height',16).attr('rx',3).attr('fill',color),v,name+' · '+(flag?'With':'Without'),posts,`${escMetric[metric]}: ${fmt(val)}`);label(s,w-22,yy+12,`${flag?'With':'Without'}: ${fmt(val)} · n=${posts.length}`,11,ink,'end')})});v.insight.text('With and without the feature, within the chosen year. These are descriptive comparisons, not evidence of a causal effect.');}
function tiles(v,rows,order,groupKey){let data=[...rows];data.sort(order==='comments'?(a,b)=>(b.comments??-1)-(a.comments??-1):order==='reactions'?(a,b)=>(b.reactions??-1)-(a.reactions??-1):order==='rank'?(a,b)=>(a.rank??9999)-(b.rank??9999):order==='old'?(a,b)=>a.date.localeCompare(b.date):(a,b)=>b.date.localeCompare(a.date));const stateKey=order+'|'+groupKey+'|'+data.map(p=>p.id).join(',');if(v.tileKey!==stateKey){v.tileKey=stateKey;v.tileLimit=48;v.compareIds=[]}const visible=data.slice(0,v.tileLimit);const groups=groupKey?d3.groups(visible,p=>p[groupKey]):[['Selected posts',visible]];groups.forEach(([name,posts])=>{v.chart.append('h3').text(`${name} · ${posts.length} shown`);const grid=v.chart.append('div').attr('class','explore-mosaic');posts.forEach(p=>{const b=grid.append('button').attr('aria-label',`${p.title}, ${p.date}, open post`).on('click',()=>{if(v.imageMode?.()==='compare'){v.compareIds||=[];if(v.compareIds.includes(p.id))v.compareIds=v.compareIds.filter(id=>id!==p.id);else{if(v.compareIds.length===2)v.compareIds=[];v.compareIds.push(p.id)}v.selection.html('');v.selection.append('span').text(v.compareIds.length===1?'One visual selected. Choose a second to compare.':'Choose two visuals to compare.');if(v.compareIds.length===2)compareVisuals(v.compareIds.map(id=>index.get(id)));}else showPost(p)});if(p.embedded)b.append('img').attr('src',p.embedded).attr('loading','lazy').attr('alt',p.title);else b.append('span').text('No visual');b.append('small').text(`${p.date} · #${p.index}`);b.append('small').text(`${fmt(p.reactions)} reactions · ${fmt(p.comments)} comments`)})});if(visible.length<data.length)v.chart.append('button').attr('class','more-visuals').text(`Show ${Math.min(48,data.length-visible.length)} more visuals`).on('click',()=>{v.tileLimit+=48;v.draw()});v.insight.text(`${visible.length} of ${data.length} matching posts shown. ${v.imageMode?.()==='compare'?'Choose two images to compare their artwork, captions and response.':'Select an image to read the post.'} Image proportions are preserved; ordering uses package counters.`);}
function tagView(v,rows,focus,minimum,mode){const tags=Object.keys(S.tag_counts),names=tags.map(t=>TN[t]),tagRows=t=>rows.filter(p=>p.baseline?.topic_tags?.includes(t)),pairs=[];tags.forEach((a,i)=>tags.slice(i+1).forEach(b=>{const posts=tagRows(a).filter(p=>p.baseline.topic_tags.includes(b)),union=new Set([...tagRows(a),...tagRows(b)]).size;pairs.push({a,b,posts,n:posts.length,jaccard:union?100*posts.length/union:0})}));if(mode==='network'){const {s,w}=base(v,Math.max(360,wGuess(v)*.65)),h=Math.max(360,w*.65),cx=w/2,cy=h/2,r=Math.min(w*.32,h*.31),pos=Object.fromEntries(tags.map((t,i)=>[t,[cx+r*Math.cos(-Math.PI/2+i*Math.PI/3),cy+r*Math.sin(-Math.PI/2+i*Math.PI/3)]]));pairs.filter(g=>g.n>=minimum&&(focus==='all'||g.a===focus||g.b===focus)).forEach(g=>{const a=pos[g.a],b=pos[g.b];mark(s.append('line').attr('x1',a[0]).attr('y1',a[1]).attr('x2',b[0]).attr('y2',b[1]).attr('stroke','#0A97D9').attr('stroke-width',2+Math.sqrt(g.n)).attr('opacity',.55),v,TN[g.a]+' + '+TN[g.b],g.posts,`${g.n} co-mentions · ${fmt(g.jaccard)}% overlap`)});tags.forEach((t,i)=>{const [x,y]=pos[t],posts=tagRows(t);mark(s.append('circle').attr('cx',x).attr('cy',y).attr('r',18+Math.sqrt(posts.length)).attr('fill',TC[t]),v,TN[t],posts,`${posts.length} tagged captions`);label(s,x,y+5,String(i+1),14,lightLabel(TC[t])?'white':ink,'middle',600).style('pointer-events','none')});v.key.text(names.map((n,i)=>`${i+1}. ${n}`).join(' · '));}else{const {s,w}=base(v,360),left=34,cw=(w-left-12)/6;names.forEach((n,i)=>label(s,left+(i+.5)*cw,24,String(i+1),12,ink,'middle',600));tags.forEach((a,i)=>{label(s,16,62+i*46,String(i+1),12,ink,'middle',600);tags.forEach((b,j)=>{const posts=tagRows(a).filter(p=>p.baseline.topic_tags.includes(b)),union=new Set([...tagRows(a),...tagRows(b)]).size,val=mode==='jaccard'?(union?100*posts.length/union:0):posts.length,max=mode==='jaccard'?100:d3.max(tags,t=>tagRows(t).length)||1,fill=d3.interpolateRgb('#EDF4FA',blue)(val/max),x=left+j*cw,y=39+i*46;mark(s.append('rect').attr('x',x).attr('y',y).attr('width',cw-3).attr('height',41).attr('rx',3).attr('fill',fill),v,TN[a]+' + '+TN[b],posts,`${fmt(val)}${mode==='jaccard'?'% overlap':' co-mentions'}`);label(s,x+(cw-3)/2,y+25,mode==='jaccard'?Math.round(val)+'%':val,10,lightLabel(fill)?'white':ink,'middle',600).style('pointer-events','none')})});v.key.text(names.map((n,i)=>`${i+1}. ${n}`).join(' · '));}v.insight.text(mode==='jaccard'?'Overlap = captions mentioning both tags ÷ captions mentioning either tag. Select a pair to inspect it.':'Select a connection or node to read its captions. Tags can overlap; counts are not unique-post totals.');}
function wGuess(v){return v.chart.node().clientWidth}
function concentration(v,rows,metric){const sorted=rows.filter(p=>numeric(p,metric)).sort((a,b)=>b[metric]-a[metric]),total=totalOf(sorted,metric),{s,w,h}=base(v,310),x=d3.scaleLinear().domain([0,100]).range([45,w-20]),y=d3.scaleLinear().domain([0,100]).range([h-45,20]);let sum=0;const points=[{x:0,y:0,n:0},...sorted.map((p,i)=>({x:(i+1)/sorted.length*100,y:total?(sum+=p[metric])/total*100:0,n:i+1}))];s.append('g').attr('transform',`translate(0,${h-45})`).call(d3.axisBottom(x).ticks(5).tickFormat(d=>d+'%'));s.append('g').attr('transform','translate(45,0)').call(d3.axisLeft(y).ticks(4).tickFormat(d=>d+'%'));s.append('path').datum(points).attr('d',d3.area().x(d=>x(d.x)).y0(h-45).y1(d=>y(d.y))).attr('fill','#DFF0FB');s.append('path').datum(points).attr('d',d3.line().x(d=>x(d.x)).y(d=>y(d.y))).attr('stroke',blue).attr('stroke-width',3).attr('fill','none');[10,25,50].forEach(percent=>{const n=Math.ceil(sorted.length*percent/100),p=points[n];if(!p)return;mark(s.append('circle').attr('cx',x(p.x)).attr('cy',y(p.y)).attr('r',7).attr('fill',red),v,`Top ${percent}% of selected posts`,sorted.slice(0,n),`${fmt(p.y)}% of ${metric} · ${n} posts`)});label(s,w/2,h-6,'Share of posts, highest response first',11,muted,'middle');v.insight.text('Select the 10%, 25% or 50% point to reveal which posts account for that share of response.');}
function monthlyScatter(v,rows,metric){const groups=d3.groups(rows,p=>p.month).map(([month,posts])=>({month,posts,words:medianOf(posts,'words'),value:medianOf(posts,metric)})).filter(g=>g.words!=null&&g.value!=null),{s,w,h}=base(v,320),x=d3.scaleLinear().domain([0,d3.max(groups,g=>g.words)||1]).nice().range([45,w-22]),y=d3.scaleLinear().domain([0,d3.max(groups,g=>g.value)||1]).nice().range([h-48,24]);s.append('g').attr('transform',`translate(0,${h-48})`).call(d3.axisBottom(x).ticks(4));s.append('g').attr('transform','translate(45,0)').call(d3.axisLeft(y).ticks(4));groups.forEach(g=>mark(s.append('circle').attr('cx',x(g.words)).attr('cy',y(g.value)).attr('r',Math.max(5,Math.sqrt(g.posts.length)*3)).attr('fill',YC[g.month.slice(0,4)]).attr('opacity',.85),v,g.month,g.posts,`${fmt(g.words)} median words · ${fmt(g.value)} median ${metric} · n=${g.posts.length}`));label(s,w/2,h-10,'Median caption words',12,muted,'middle');label(s,45,14,'Median '+metric,12,muted);v.insight.text('Each bubble is a month; size represents its caption sample. Select a month to inspect the posts behind it.');}
function audit(v,rows){const groups=[['Author caption',p=>!!p.caption],['Main image',p=>!!p.image],['Activity ID',p=>!!p.activityId],['Exact UTC time',p=>!!p.baseline?.published]];const {s,w}=base(v,320);groups.forEach(([name,fn],i)=>{const yes=rows.filter(fn),no=rows.filter(p=>!fn(p)),y=25+i*70;label(s,16,y,name,13,ink,'start',600);label(s,w-16,y,`${yes.length} / ${rows.length}`,12,muted,'end');const full=w-32,a=rows.length?full*yes.length/rows.length:0;mark(s.append('rect').attr('x',16).attr('y',y+12).attr('width',a).attr('height',24).attr('rx',3).attr('fill',blue),v,name+' available',yes,'Verified in recovered dataset');mark(s.append('rect').attr('x',16+a).attr('y',y+12).attr('width',full-a).attr('height',24).attr('rx',3).attr('fill','#FCC30B'),v,name+' missing',no,'Unresolved in recovered dataset')});v.key.text('Blue: available · Yellow: missing / unresolved');v.insight.text('Select a missing segment to inspect the records that still need attention. This measures the recovered archive, not account completeness.');}
function counterChanges(v,rows,field,sort){const ids=new Set(rows.map(p=>p.id)),changes=D.differences.filter(d=>ids.has(d.activity_id)&&(field==='all'||d.field===field)).sort(sort==='size'?(a,b)=>Math.abs(b.difference)-Math.abs(a.difference):(a,b)=>index.get(a.activity_id).date.localeCompare(index.get(b.activity_id).date));const {s,w}=base(v,changes.length*52+30),max=d3.max(changes,d=>Math.abs(d.difference))||1,x=d3.scaleLinear().domain([-max,max]).range([20,w-20]);changes.forEach((d,i)=>{const p=index.get(d.activity_id),y=20+i*52;label(s,16,y,`#${p.index} · ${p.date} · ${d.field==='reactions'?'Reactions':'Comments'}`,12,ink);label(s,w-16,y,`${d.package_value} → ${d.browser_value}`,12,muted,'end');s.append('line').attr('x1',x(0)).attr('x2',x(d.difference)).attr('y1',y+19).attr('y2',y+19).attr('stroke',d.difference<0?red:blue).attr('stroke-width',4);mark(s.append('circle').attr('cx',x(d.difference)).attr('cy',y+19).attr('r',7).attr('fill',d.difference<0?red:blue),v,p.title,[p],`Change ${d3.format('+d')(d.difference)}`)});v.insight.text(`${changes.length} recorded differences. Reorder by magnitude to investigate the largest changes; the reason for each difference is unverified.`);}
function pairView(v,pair,metric){v.scope.text('Independent comparison · two publications · page year filter does not apply');const posts=pair.posts.map(d=>{const match=d.url.match(/activity-(\d+)/);return match?index.get(match[1]):null}).filter(Boolean);const {s,w}=base(v,210),max=d3.max(posts,p=>p[metric])||1,x=d3.scaleLinear().domain([0,max]).range([16,w-20]);posts.forEach((p,i)=>{const y=32+i*85;label(s,16,y,`${i?'Second':'First'} publication · ${p.date}`,13,ink,'start',600);mark(s.append('rect').attr('x',16).attr('y',y+15).attr('width',Math.max(2,x(p[metric])-16)).attr('height',23).attr('rx',4).attr('fill',i?red:blue),v,p.title,[p],`${fmt(p[metric])} ${metric}`);label(s,w-20,y,fmt(p[metric]),14,ink,'end',600)});v.insight.text('Select either publication to read its text and compare context. Similar text does not isolate the cause of different response.');}
function planner(v,topic,test){v.scope.text('Editorial experiment builder · page year filter does not apply');const texts={opening:['Opening','A: open with the finding.','B: open with a specific professional question.','Keep the evidence, visual and call to action comparable.'],visual:['Visual','A: one explanatory chart.','B: one concrete photograph.','Keep the claim and caption structure comparable.'],approach:['Approach','A: report a decision from an event.','B: explain the same decision as a practical argument.','Keep topic and audience comparable.']},t=texts[test];v.chart.append('h3').text(`${topic==='all'?'One concrete topic':topic}: ${t[0].toLowerCase()} comparison`);const grid=v.chart.append('div').attr('class','experiment-pair');t.slice(1,3).forEach((text,i)=>grid.append('div').attr('class','experiment-option').append('p').text(text));v.chart.append('p').text(t[3]);v.chart.append('p').text('Record each post’s seven-day impressions, saves and substantive comments if account analytics are available. Compare several matched pairs before drawing a conclusion.');const examples=exploreRows.filter(p=>topic==='all'||p.topic===topic).sort((a,b)=>(b.comments??-1)-(a.comments??-1)).slice(0,6);v.chart.append('button').text(`Study ${examples.length} relevant examples`).on('click',()=>openRowsDialog(examples,'Examples to inform the experiment'));v.insight.text('A planning tool, not a performance prediction. Changing the choices updates the proposed comparison.');}
function setupExplorer(article){const spec=F.find(f=>f.id===article.id),a=d3.select(article),v={spec};const original=article.querySelector('.svgstage');const snapshot=document.createElement('details');snapshot.className='report-snapshot';const summary=document.createElement('summary');summary.textContent='Original report figure';snapshot.append(summary);original.before(snapshot);snapshot.append(original);snapshot.append(article.querySelector('.exports'));snapshot.append(article.querySelector('.figuretext'));const host=a.insert('section','.report-snapshot').attr('class','data-explorer').attr('aria-label',spec.title+' data explorer');v.controls=host.append('div').attr('class','data-controls');v.scope=host.append('p').attr('class','data-scope');v.chart=host.append('div').attr('class','live-chart');v.key=host.append('div').attr('class','data-key');v.insight=host.append('p').attr('class','data-insight');v.selection=host.append('div').attr('class','data-selection').attr('aria-live','polite');
 const id=spec.id;let render,source=exploreRows,usesYear=true,pairKeys=null,activeMetric=null,pairWhen=()=>true;
 const metric=()=>{pairKeys=['reactions','comments'];return ()=>activeMetric||'reactions'};
 const topicControl=()=>control(v,'Topic',[['all','All topics'],...unique('topic')],'all');
 let filterTopic=null,filterApproach=null;
 if(['f05','f15','f19','f21','f22','f25','f30'].includes(id))filterTopic=topicControl();
 if(id==='f01'){source=P;render=rows=>calendar(v,rows,'count');}
 else if(id==='f03'){const m=metric();render=rows=>calendar(v,rows,m());}
 else if(id==='f02'){const m=metric(),interval=control(v,'Interval',[['quarter','Quarter'],['month','Month']]);render=rows=>timeline(v,rows,m(),interval());}
 else if(id==='f04'){pairKeys=['words','ai'];render=rows=>categoryBars(v,rows,'year',activeMetric,'name');}
 else if(id==='f05'){const m=metric();render=rows=>monthlyScatter(v,rows,m());}
 else if(['f06','f22'].includes(id)){source=rankRows;const rank=control(v,'Sort by',[['rank','Original composite rank'],['reactions','Reactions (highest first)'],['comments','Comments (highest first)']]),limit=control(v,'Show',[['10','Top 10'],['24','Top 24'],['50','Top 50']],id==='f06'?'10':'24');render=rows=>{const sorted=[...rows].sort(rank()==='rank'?(a,b)=>a.rank-b.rank:(a,b)=>b[rank()]-a[rank()]);tiles(v,sorted.slice(0,+limit()),rank(),null);};}
 else if(id==='f07'){render=rows=>composition(v,rows,'topic');}
 else if(id==='f09'){const m=metric(),order=control(v,'Sort by',[['name','Name (A–Z)'],['volume','Post count (highest first)']]);render=rows=>{v.categoryOrder=d3.groups(rows,p=>p.approach).sort(order()==='volume'?(a,b)=>b[1].length-a[1].length:(a,b)=>a[0].localeCompare(b[0])).map(g=>g[0]);categoryBars(v,rows,'approach',m(),order())};}
 else if(id==='f08'){render=rows=>{topicMap(v,rows);v.chart.append('h3').attr('class','comparison-heading').text('Ranked topic comparisons');pairedPanels(v,['reactions','comments'],key=>categoryBars(v,rows,'topic',key,'value',key==='comments'?'#89949D':'#526B7C'));v.insight.text('Map and rankings use the same selected captions. Each ranking sorts from highest to lowest median; select a topic in any view to inspect its posts.');};}
 else if(['f10','f11'].includes(id)){const m=metric(id==='f10'?'reactions':'comments',[['count','Caption count']]);filterApproach=control(v,'Approach',[['all','All approaches'],...unique('approach')]);render=rows=>matrix(v,rows,'topic','approach',m());}
 else if(id==='f12'){usesYear=false;const m=metric(),first=control(v,'Compare',years,'2024'),second=control(v,'Against',years,'2026');render=rows=>compareYears(v,rows,'approach',m(),first(),second());}
 else if(id==='f13'){filterTopic=topicControl();render=rows=>composition(v,rows,'approach');}
 else if(id==='f14'){const focus=control(v,'Follow a connection',[['all','All tags'],...Object.keys(S.tag_counts).map(t=>[t,TN[t]])]),minimum=control(v,'Minimum shared captions',[['1','1+'],['10','10+'],['20','20+'],['40','40+']],'10');render=rows=>tagView(v,rows,focus(),+minimum(),'network');}
 else if(id==='f15'){source=rankRows;const view=control(v,'Investigate',[['concentration','Who accounts for the response?'],['scatter','Reactions versus comments']]),m=metric();v.brushMode=control(v,'Selection',[['inspect','Inspect a post'],['select','Select a region']]);pairWhen=()=>view()==='concentration';render=rows=>{v.controls.selectAll('label,.control-field').filter((d,i)=>i===2).attr('hidden',view()==='scatter'?null:true);if(view()==='scatter')scatterExplore(v,rows,'reactions','comments');else concentration(v,rows,m())};}
 else if(id==='f16'||id==='f24'){const m=metric();render=rows=>featureCompare(v,rows,m(),id==='f16');}
 else if(id==='f17'){usesYear=false;const pair=control(v,'Publication pair',S.pairs.map((p,i)=>[String(i),p.label])),m=metric();render=()=>pairView(v,S.pairs[+pair()],m());}
 else if(id==='f18'){source=P;render=rows=>audit(v,rows);}
 else if(['f19','f20','f21'].includes(id)){source=P;if(!filterTopic)filterTopic=topicControl();v.imageMode=control(v,'On image selection',[['read','Read the post'],['compare','Compare two visuals']]);const groupBy=control(v,'Arrange by',[['year','Year'],['topic','Topic'],['palette','Colour family'],['type','Visual type']],id==='f20'?'topic':id==='f21'?'palette':'year'),sort=control(v,'Sort by',[['new','Newest first'],['old','Oldest first'],['reactions','Most reactions'],['comments','Most comments']]);render=rows=>tiles(v,rows,sort(),groupBy());}
 else if(id==='f23'){const m=metric();render=rows=>distribution(v,rows,m());}
 else if(id==='f25'){const m=metric();v.brushMode=control(v,'Selection',[['inspect','Inspect a post'],['select','Select a region']]);render=rows=>scatterExplore(v,rows,'words',m());}
 else if(id==='f26'){source=P.filter(p=>p.image);const groupBy=control(v,'Group visuals by',[['type','Asset type'],['palette','Colour family'],['topic','Topic']]);render=rows=>categoryBars(v,rows,groupBy(),'count');}
 else if(id==='f27'){const mode=control(v,'Relationship',[['count','Shared caption count'],['jaccard','Overlap percentage']]);render=rows=>tagView(v,rows,'all',1,mode());}
 else if(id==='f28'){source=P;const field=control(v,'Counter',[['all','Both counters'],['reactions','Reactions'],['comment_count','Comments']]),sort=control(v,'Sort by',[['size','Largest change'],['date','Date (oldest first)']]);render=rows=>counterChanges(v,rows,field(),sort());}
 else if(id==='f29'){usesYear=false;const topic=topicControl(),test=control(v,'Test one choice',[['opening','Opening'],['visual','Visual'],['approach','Writing approach']]);render=()=>planner(v,topic(),test());}
 else if(id==='f30'){source=P.filter(p=>p.image);const shape=control(v,'Shape',[['all','All shapes'],['portrait','Portrait'],['square','Near square'],['landscape','Landscape']]),sort=control(v,'Sort by',[['new','Newest first'],['old','Oldest first'],['reactions','Most reactions'],['comments','Most comments']]);render=rows=>tiles(v,rows.filter(p=>shape()==='all'||(shape()==='portrait'?p.width/p.height<.9:shape()==='square'?p.width/p.height>=.9&&p.width/p.height<=1.1:p.width/p.height>1.1)),sort(),null);}
 v.draw=()=>{hover.attr('hidden',true);v.chart.html('');v.key.text('');v.selection.html('');const rows=source.filter(p=>(!usesYear||exploreYear==='all'||p.year===exploreYear)&&(!filterTopic||filterTopic()==='all'||p.topic===filterTopic())&&(!filterApproach||filterApproach()==='all'||p.approach===filterApproach()));v.scope.text(`${usesYear?(exploreYear==='all'?'All recovered years':exploreYear):'Independent comparison'} · ${rows.length} ${source===exploreRows?'eligible original captions':source===rankRows?'rankable original posts':'recovered records'}${!usesYear?' · page year filter does not apply':''}`);if(!rows.length&&id!=='f29'){v.chart.append('p').attr('class','explore-empty').text('No records match this selection. Choose another year or topic.');v.insight.text('An empty recovered sample does not mean no posts were published.');return;}try{if(pairKeys&&pairWhen())pairedPanels(v,pairKeys,key=>{activeMetric=key;render(rows)});else render(rows)}catch(error){v.chart.append('p').text('This view could not render. The report snapshot remains available.');console.error(id,error)}};
 let lastWidth=0;new ResizeObserver(entries=>{const width=Math.round(entries[0].contentRect.width);if(width&&Math.abs(width-lastWidth)>2){lastWidth=width;v.draw()}}).observe(host.node());v.draw();explorers.push(v);
}
document.querySelectorAll('article.figure').forEach(setupExplorer);
function topicMap(v,rows){
 const groups=d3.groups(rows,p=>p.topic).map(([name,posts])=>({name,posts,x:medianOf(posts,'reactions'),y:medianOf(posts,'comments')})).filter(g=>g.x!=null&&g.y!=null);
 if(!groups.length){v.chart.append('p').text('No topic has three known observations for both measures in this selection.');return;}
 const {s,w,h}=base(v,wGuess(v)<500?590:510),mobile=w<500,left=48,right=w-22,top=100,bottom=h-115;
 const mx=medianOf(rows,'reactions'),my=medianOf(rows,'comments');
 const extent=(key,benchmark)=>{const vals=[...groups.map(g=>g[key]),benchmark].filter(n=>n!=null),lo=d3.min(vals),hi=d3.max(vals),pad=Math.max((hi-lo)*.24,key==='x'?8:1);return [Math.max(0,lo-pad),hi+pad]};
 const x=d3.scaleLinear().domain(extent('x',mx)).nice().range([left,right]),y=d3.scaleLinear().domain(extent('y',my)).nice().range([bottom,top]);
 s.append('g').attr('transform',`translate(0,${bottom})`).call(d3.axisBottom(x).ticks(mobile?4:7));
 s.append('g').attr('transform',`translate(${left},0)`).call(d3.axisLeft(y).ticks(5).tickSize(-(right-left))).call(g=>g.selectAll('line').attr('stroke','#E8EDF2')).call(g=>g.select('.domain').remove());
 if(mx!=null)s.append('line').attr('x1',x(mx)).attr('x2',x(mx)).attr('y1',top).attr('y2',bottom).attr('stroke','#52647A').attr('stroke-dasharray','5 5');
 if(my!=null)s.append('line').attr('x1',left).attr('x2',right).attr('y1',y(my)).attr('y2',y(my)).attr('stroke','#52647A').attr('stroke-dasharray','5 5');
 const r=d3.scaleSqrt().domain([0,d3.max(groups,g=>g.posts.length)]).range([0,mobile?22:34]);
 const occupied=groups.map(g=>({x:x(g.x)-r(g.posts.length)-3,y:y(g.y)-r(g.posts.length)-3,w:2*r(g.posts.length)+6,h:2*r(g.posts.length)+6}));
 const overlaps=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
 const labels=[];
 groups.slice().sort((a,b)=>b.posts.length-a.posts.length).forEach(g=>{
  const px=x(g.x),py=y(g.y),bw=mobile?116:160,lines=[];let line='';g.name.split(' ').forEach(word=>{if((line+' '+word).trim().length>(mobile?17:23)&&line){lines.push(line);line=word}else line=(line+' '+word).trim()});if(line)lines.push(line);
  const bh=lines.length*15+20,candidates=[];
  for(const dist of [r(g.posts.length)+12,65,100,145,200,260])for(const angle of [-Math.PI/2,Math.PI/2,0,Math.PI,-Math.PI/4,-3*Math.PI/4,Math.PI/4,3*Math.PI/4]){const cx=px+Math.cos(angle)*(dist+bw/2),cy=py+Math.sin(angle)*(dist+bh/2);const box={x:Math.max(4,Math.min(w-bw-4,cx-bw/2)),y:Math.max(26,Math.min(h-52-bh,cy-bh/2)),w:bw,h:bh};const score=occupied.filter(o=>overlaps(box,o)).length*100000+Math.hypot(box.x+bw/2-px,box.y+bh/2-py);candidates.push({...box,score})}
  const best=candidates.sort((a,b)=>a.score-b.score)[0];occupied.push(best);labels.push({g,lines,box:best});
 });
 labels.forEach(({g,box})=>s.append('line').attr('x1',x(g.x)).attr('y1',y(g.y)).attr('x2',Math.max(box.x,Math.min(box.x+box.w,x(g.x)))).attr('y2',Math.max(box.y,Math.min(box.y+box.h,y(g.y)))).attr('stroke',D.colors[g.name]||blue).attr('stroke-width',1.3));
 groups.forEach(g=>mark(s.append('circle').attr('cx',x(g.x)).attr('cy',y(g.y)).attr('r',r(g.posts.length)).attr('fill',D.colors[g.name]||blue).attr('stroke','white').attr('stroke-width',2).attr('opacity',.94),v,g.name,g.posts,`Median ${fmt(g.x)} reactions · ${fmt(g.y)} comments · n=${g.posts.length}`));
 labels.forEach(({g,lines,box})=>{const group=s.append('g');group.append('rect').attr('x',box.x).attr('y',box.y).attr('width',box.w).attr('height',box.h).attr('rx',4).attr('fill','white').attr('fill-opacity',.95);lines.forEach((text,i)=>label(group,box.x+5,box.y+13+i*15,text,12,ink,'start',700));label(group,box.x+5,box.y+13+lines.length*15,`n=${g.posts.length} · ${fmt(g.x)} / ${fmt(g.y)}`,11,muted);mark(group,v,g.name,g.posts,`Median ${fmt(g.x)} reactions · ${fmt(g.y)} comments · n=${g.posts.length}`)});
 label(s,w/2,h-12,'Median reactions →',12,muted,'middle');label(s,left,16,'Median comments ↑',12,muted);
 v.chart.append('p').attr('class','map-reading-note').text(`Bubble area = caption count. Labels show n, median reactions / comments. Dashed benchmarks: ${fmt(mx)} reactions and ${fmt(my)} comments across selected captions. Axes focus on the observed topic range.`);
}

function compareVisuals(posts){let dlg=document.querySelector('#visual-compare');if(!dlg){dlg=document.createElement('dialog');dlg.id='visual-compare';dlg.setAttribute('aria-label','Compare two post visuals');document.body.append(dlg)}const root=d3.select(dlg);root.html('');root.append('button').attr('class','close').attr('aria-label','Close visual comparison').text('Close ×').on('click',()=>dlg.close());root.append('h2').style('clear','both').style('padding-top','20px').text('Two posts, side by side');root.append('p').text('Compare the visual choice and the message. Public counters do not isolate the effect of the image.');const grid=root.append('div').attr('class','visual-comparison');posts.forEach(p=>{const card=grid.append('section');if(p.embedded)card.append('img').attr('src',p.embedded).attr('alt',p.title);card.append('small').text(p.date+' · #'+p.index);card.append('h3').text(p.title);card.append('p').attr('class','compare-numbers').text(`${fmt(p.reactions)} reactions · ${fmt(p.comments)} comments`);card.append('p').text(`${p.words} words · ${p.topic} · ${p.approach}`);card.append('p').attr('class','compare-caption').text(p.caption||p.sharedText||'No author caption recovered.');card.append('button').text('Read full post').on('click',()=>{dlg.close();showPost(p)})});dlg.showModal();dlg.scrollTop=0;}

function pairedPanels(v,keys,draw){
 const original={chart:v.chart,key:v.key,insight:v.insight};
 const grid=original.chart.append('div').attr('class','paired-metrics');
 try{keys.forEach(key=>{const panel=grid.append('section').attr('class','metric-panel').attr('data-metric',key);panel.append('h3').text(key==='reactions'?'Reactions':key==='comments'?'Comments':escMetric[key]||key);v.chart=panel.append('div').attr('class','metric-plot');v.key=panel.append('div').attr('class','data-key');v.insight=panel.append('p').attr('class','data-insight');draw(key)});}finally{Object.assign(v,original)}
 v.insight.text('Both measures use the same selected records, with separate scales. Select a mark in either chart to inspect its source posts.');
}
function composition(v,rows,field){
 const groups=d3.groups(rows,p=>p[field]),{s,w}=base(v,300),colors=field==='topic'?D.colors:Object.fromEntries(Object.entries(AN).map(([key,name])=>[name,AC[key]]));
 [['count','Posts'],['reactions','Reactions'],['comments','Comments']].forEach(([key,name],i)=>{const y=25+i*88,total=key==='count'?rows.length:totalOf(rows,key);label(s,12,y,name,14,ink,'start',600);label(s,w-12,y,`${fmt(total)} total`,12,muted,'end');let offset=12;groups.forEach(([group,posts])=>{const n=key==='count'?posts.length:totalOf(posts,key),share=total?n/total:0,width=(w-24)*share;if(width>0){mark(s.append('rect').attr('x',offset).attr('y',y+14).attr('width',width).attr('height',38).attr('fill',colors[group]||blue),v,`${group} · ${name}`,posts,`${fmt(n)} ${name.toLowerCase()} · ${fmt(share*100)}% of selected total`);if(width>40)label(s,offset+width/2,y+38,Math.round(share*100)+'%',11,lightLabel(colors[group]||blue)?'white':ink,'middle',600).style('pointer-events','none')}offset+=width});if(!total)label(s,12,y+40,'No recorded response in this selection',12,muted);});
 const legend=v.chart.append('div').attr('class','composition-legend');groups.forEach(([name,posts])=>{const button=legend.append('button').on('click',()=>addSelection(v,name,posts,`${posts.length} posts · ${totalOf(posts,'reactions')} reactions · ${totalOf(posts,'comments')} comments`));button.append('span').style('background',colors[name]||blue);button.append('span').text(name)});
 v.insight.text('The three bars show each group’s share of posts, reactions and comments. Select a segment or legend label to inspect the underlying posts.');
}
